### ISSUE TITLE
Publisher ID cause session conflict when Keycloak has more one node.

### ISSUE THREAD

**Issue by ronaldocherokee** [softwarefactory-project/keycloak-event-listener-mqtt#11]
When Keycloak has more one node, MQTT server (Mosquitto) has constant login/logout causing connection failures.

Publisher_ID has static in MQTTEventListenerProviderFactory.java.

I sugest an enviromment variable.

**Comment by mhuin** [comment]
Thanks for reporting the issue, do you want to provide a patch for this?

**Comment by NicoV1994** [comment]
Is there an update/fix for this?

**Comment by mhuin** [comment]
Publisher ID is now a parameter.
