### ISSUE TITLE
Verbose logging of event listener configuration

### ISSUE THREAD

**Issue by sbaeurle** [softwarefactory-project/keycloak-event-listener-mqtt#5]
Hey, I did check the source code to verify the origin of the following log statement issued by the event listener:

`MQTT Event Listener configured to use server ssl://***:1883 with username ***`

However I was not able to find any configuration or code statements related to the output.

Since this occurs quite frequently (for each Keycloak event), I was wondering if and how to disable this

**Comment by mhuin** [comment]
Hello,
This is odd, I could not find any reference to such a message either. Maybe you can try to change the logging level for this specific module, see https://www.keycloak.org/server/logging#_configuring_category_specific_log_levels

**Comment by sbaeurle** [comment]
okay, I did set `KC_LOG_LEVEL=info,org.softwarefactory.keycloak.providers.events.mqtt:fatal`.
However the interesting log output still occurs!

**Comment by sbaeurle** [comment]
@mhuin I did verify it in our keycloak instance. the verbose logging is not occuring in the new version anymore! However I do need to make a small adjustment regarding the exception logging (see https://softwarefactory-project.io/r/c/software-factory/keycloak-event-listener-mqtt/+/27870)
