### ISSUE TITLE
not always create new connection on every event

### ISSUE THREAD

**Issue by arigelni** [softwarefactory-project/keycloak-event-listener-mqtt#6]
Hi, 
is it possible to not always create mqtt connection on every event?
the performance goes very fast down...
a connection handler which holds a connection would helpful?

**Comment by sbaeurle** [comment]
We did also need this change and created the following PR for it: https://softwarefactory-project.io/r/c/software-factory/keycloak-event-listener-mqtt/+/27905

**Comment by mhuin** [comment]
the change @sbaeurle mentioned was merged and should fix the issue.
