### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by eigood** [softwarefactory-project/keycloak-event-listener-mqtt#7]
https://github.com/softwarefactory-project/keycloak-event-listener-mqtt/blob/b96a1183bf808e61509f8a4c37fdf650225ffeec/README.md?plain=1#L60

The above line should say "use-persistence" not "user-persistence".  That's based on the Wildfly configuration snippet given just above.

**Comment by mhuin** [comment]
Thanks for reporting! This has been fixed.

**Comment by eigood** [comment]
Great, thank you
